<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_sidebarBg2f3136,sidebarTextffffff,_c82985</name>
   <tag></tag>
   <elementGuidId>f2744511-7d2c-40be-adc3-cb7d639b168e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pasteBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='pasteBox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pasteBox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>{&quot;sidebarBg&quot;:&quot;#2f3136&quot;,&quot;sidebarText&quot;:&quot;#ffffff&quot;,&quot;sidebarUnreadText&quot;:&quot;#ffffff&quot;,&quot;sidebarTextHoverBg&quot;:&quot;#33363c&quot;,&quot;sidebarTextActiveBorder&quot;:&quot;#66cfa0&quot;,&quot;sidebarTextActiveColor&quot;:&quot;#ffffff&quot;,&quot;sidebarHeaderBg&quot;:&quot;#27292c&quot;,&quot;sidebarHeaderTextColor&quot;:&quot;#ffffff&quot;,&quot;onlineIndicator&quot;:&quot;#43b581&quot;,&quot;awayIndicator&quot;:&quot;#faa61a&quot;,&quot;dndIndicator&quot;:&quot;#f04747&quot;,&quot;mentionBg&quot;:&quot;#6e84d2&quot;,&quot;mentionColor&quot;:&quot;#ffffff&quot;,&quot;centerChannelBg&quot;:&quot;#36393f&quot;,&quot;centerChannelColor&quot;:&quot;#dddddd&quot;,&quot;newMessageSeparator&quot;:&quot;#6e84d2&quot;,&quot;linkColor&quot;:&quot;#2095e8&quot;,&quot;buttonBg&quot;:&quot;#43b581&quot;,&quot;buttonColor&quot;:&quot;#ffffff&quot;,&quot;errorTextColor&quot;:&quot;#ff6461&quot;,&quot;mentionHighlightBg&quot;:&quot;#3d414f&quot;,&quot;mentionHighlightLink&quot;:&quot;#6e84d2&quot;,&quot;codeTheme&quot;:&quot;monokai&quot;,&quot;mentionBj&quot;:&quot;#ffffff&quot;}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pasteBox&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='pasteBox']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='displaySettings']/div[2]/div[2]/section/div/div/div/div[3]/div/div[4]/div/textarea</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy and paste to share theme colors:'])[1]/following::textarea[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Button Text'])[1]/following::textarea[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Theme Colors'])[1]/preceding::textarea[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✔ Copied'])[1]/preceding::textarea[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='{&quot;sidebarBg&quot;:&quot;#2f3136&quot;,&quot;sidebarText&quot;:&quot;#ffffff&quot;,&quot;sidebarUnreadText&quot;:&quot;#ffffff&quot;,&quot;sidebarTextHoverBg&quot;:&quot;#33363c&quot;,&quot;sidebarTextActiveBorder&quot;:&quot;#66cfa0&quot;,&quot;sidebarTextActiveColor&quot;:&quot;#ffffff&quot;,&quot;sidebarHeaderBg&quot;:&quot;#27292c&quot;,&quot;sidebarHeaderTextColor&quot;:&quot;#ffffff&quot;,&quot;onlineIndicator&quot;:&quot;#43b581&quot;,&quot;awayIndicator&quot;:&quot;#faa61a&quot;,&quot;dndIndicator&quot;:&quot;#f04747&quot;,&quot;mentionBg&quot;:&quot;#6e84d2&quot;,&quot;mentionColor&quot;:&quot;#ffffff&quot;,&quot;centerChannelBg&quot;:&quot;#36393f&quot;,&quot;centerChannelColor&quot;:&quot;#dddddd&quot;,&quot;newMessageSeparator&quot;:&quot;#6e84d2&quot;,&quot;linkColor&quot;:&quot;#2095e8&quot;,&quot;buttonBg&quot;:&quot;#43b581&quot;,&quot;buttonColor&quot;:&quot;#ffffff&quot;,&quot;errorTextColor&quot;:&quot;#ff6461&quot;,&quot;mentionHighlightBg&quot;:&quot;#3d414f&quot;,&quot;mentionHighlightLink&quot;:&quot;#6e84d2&quot;,&quot;codeTheme&quot;:&quot;monokai&quot;,&quot;mentionBj&quot;:&quot;#ffffff&quot;}']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/textarea</value>
   </webElementXpaths>
</WebElementEntity>
